apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: a0a40e76-0cd4-4904-93af-62a1e08120ff
    run.googleapis.com/build-image-uri: us-east1-docker.pkg.dev/execalc-core/cloud-run-source-deploy/execalc-api
    run.googleapis.com/build-name: projects/1052039536917/locations/us-east1/builds/a0a40e76-0cd4-4904-93af-62a1e08120ff
    run.googleapis.com/build-source-location: gs://run-sources-execalc-core-us-east1/services/execalc-api/1769823683.145768-916d66a32cff47fa87a912c8dd15a180.zip#1769823683256626
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 551.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/operation-id: 6f279434-eb26-4ee3-b164-5bd929d000e0
    run.googleapis.com/urls: '["https://execalc-api-1052039536917.us-east1.run.app","https://execalc-api-7f42ijydqa-ue.a.run.app"]'
    serving.knative.dev/creator: j.brubaker@playerscapital.net
    serving.knative.dev/lastModifier: j.brubaker@playerscapital.net
  creationTimestamp: '2026-01-31T01:43:07.804553Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-east1
  name: execalc-api
  namespace: '1052039536917'
  resourceVersion: AAZJpTcdaSI
  selfLink: /apis/serving.knative.dev/v1/namespaces/1052039536917/services/execalc-api
  uid: 279db660-c584-4924-b745-3ba5dbd8c19b
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 551.0.0
        run.googleapis.com/cloudsql-instances: execalc-core:us-east1:execalc-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: wexepkyjot
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: EXECALC_PERSIST_EXECUTIONS
          value: '1'
        - name: EXECALC_DB_NAME
          value: execalc
        - name: EXECALC_DB_USER
          value: execalc_app
        - name: EXECALC_DB_HOST
          value: /cloudsql/execalc-core:us-east1:execalc-db
        - name: EXECALC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: execalc-db-password
        image: us-east1-docker.pkg.dev/execalc-core/cloud-run-source-deploy/execalc-api@sha256:14560570e22ddc6e6adacdde2d93c80d14d99acf7c03b3247acc0cfbba6786d6
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: execalc-service-account@execalc-core.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://execalc-api-7f42ijydqa-ue.a.run.app
  conditions:
  - lastTransitionTime: '2026-01-31T01:43:23.369762Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-01-31T01:43:13.236276Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-01-31T01:43:23.338247Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: execalc-api-00001-klf
  latestReadyRevisionName: execalc-api-00001-klf
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: execalc-api-00001-klf
  url: https://execalc-api-7f42ijydqa-ue.a.run.app
